### ISSUE TITLE
hostNetwork Parameter

### ISSUE THREAD

**Issue by infinitydon** [metallb/frr-k8s#177]
Hi,

I will like to ask if it is strictly necessary to run frr-k8s with the hostNetwork set to true? I tried to disable it but the **_frr_** and _**frr-k8s**_ containers could not come up properly.

Below are the error logs

[frr.txt](https://github.com/user-attachments/files/16353537/frr.txt)
[frr-k8s.txt](https://github.com/user-attachments/files/16353538/frr-k8s.txt)

Thanks

**Comment by infinitydon** [comment]
To provide more context, I want to use VPP (plus the VPP Linux Control Plane, this allows VPP routing table to be controlled at the kernel space via routing protocols) as the forwarding plane, so I adjusted the **_allinone-frr-k8s.yaml_** manifest as follows:

```
      - command:
        - /bin/sh
        - -c
        - |
          sleep 20
          ip link add dev vrf1 type vrf table 1
          ip link set dev vrf1 up
          ip link set dev vlan100 master vrf1
          ip link set dev dpdk1 master vrf1          
          /sbin/tini -- /usr/lib/frr/docker-start &
          attempts=0
          until [[ -f /etc/frr/frr.log || $attempts -eq 60 ]]; do
            sleep 1
            attempts=$(( $attempts + 1 ))
          done
          tail -f /etc/frr/frr.log
        env:
        - name: TINI_SUBREAPER
          value: "true"
        image: quay.io/frrouting/frr:9.1.0
        livenessProbe:
          failureThreshold: 3
          httpGet:
            host: 127.0.0.1
            path: /livez
            port: 7573
          periodSeconds: 5
        name: frr
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            - NET_BIND_SERVICE
        startupProbe:
          failureThreshold: 30
          httpGet:
            host: 127.0.0.1
            path: /livez
            port: 7573
          periodSeconds: 5
        volumeMounts:
        - mountPath: /var/run/frr
          name: frr-sockets
        - mountPath: /etc/frr
          name: frr-conf
      - args:
        - --metrics-port=7573
        - --metrics-bind-address=127.0.0.1
        command:
        - /etc/frr_metrics/frr-metrics
        image: quay.io/frrouting/frr:9.1.0
        name: frr-metrics
        ports:
        - containerPort: 7573
          name: monitoring
        volumeMounts:
        - mountPath: /var/run/frr
          name: frr-sockets
        - mountPath: /etc/frr
          name: frr-conf
        - mountPath: /etc/frr_metrics
          name: metrics
      - command:
        - /etc/frr_reloader/frr-reloader.sh
        image: quay.io/frrouting/frr:9.1.0
        name: reloader
        volumeMounts:
        - mountPath: /var/run/frr
          name: frr-sockets
        - mountPath: /etc/frr
          name: frr-conf
        - mountPath: /etc/frr_reloader
          name: reloader
      - name: vpp
        image: ligato/vpp-base:24.02
        command: ["/bin/sh", "-c"]
        args:
          - |
            vpp -c /etc/vpp/startup.conf
        volumeMounts:
        - name: vpp-config
          mountPath: /etc/vpp/bootstrap.vpp
          subPath: bootstrap.vpp
        - name: vpp-startup-config
          mountPath: /etc/vpp/startup.conf
          subPath: startup.conf
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "2"
            memory: 2Gi
            hugepages-1Gi: 4Gi
          limits:
            cpu: "2"
            memory: 2Gi
            hugepages-1Gi: 4Gi
```
This works with using the hostNetwork but when I set it to false, it gives the errors as I posted previously.

In this scenarios, I don't need the hostNetwork since VPP is doing the dataplane processing via DPDK
